#!/usr/bin/env node

/**
 * Content Shield — Audit Existing Content
 * Scans mission posts to verify filter doesn't block legitimate religious/social content
 */

const fs = require('fs');
const path = require('path');
const { filterContent } = require('./filter_v2');

const missionsDir = path.join(__dirname, '..', '..', 'missions');
const reportPath = path.join(__dirname, '..', '..', 'reports', 'content_shield_audit_2026-05-11.md');

/**
 * Get all mission markdown files
 */
function getMissionFiles() {
  if (!fs.existsSync(missionsDir)) return [];
  return fs.readdirSync(missionsDir)
    .filter(f => f.endsWith('.md'))
    .map(f => path.join(missionsDir, f));
}

/**
 * Read and extract main content (skip code blocks)
 */
function readContent(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  // Remove code blocks
  content = content.replace(/```[\s\S]*?```/g, '');
  // Remove frontmatter
  content = content.replace(/^---[\s\S]*?---\n/g, '');
  return content;
}

/**
 * Run audit
 */
function audit() {
  const files = getMissionFiles();
  console.log(`🔍 Auditing ${files.length} mission files...\n`);

  const results = [];
  let falsePositives = 0;
  let passes = 0;
  let blocks = 0;

  files.forEach(file => {
    const content = readContent(file);
    const result = filterContent(content, { isReligiousContent: true, isPublishing: false });

    results.push({
      file: path.basename(file),
      action: result.action,
      reason: result.reason,
      category: result.category
    });

    if (result.action === 'pass') passes++;
    else if (result.action === 'flag_for_review') {
      falsePositives++; // Blocked but safe — needs tuning
    } else blocks++;
  });

  // Generate report
  const report = `# Content Shield Audit — ${new Date().toISOString().split('T')[0]}

**Files scanned:** ${files.length}
**Passed:** ${passes} (${((passes/files.length)*100).toFixed(1)}%)
**Flagged (potential false positives):** ${falsePositives}
**Rejected (legitimate blocks):** ${blocks}

## Flagged Files (review threshold tuning required)

${results.filter(r => r.action === 'flag_for_review').map(r => `
### ${r.file}
- **Category:** ${r.category}
- **Reason:** ${r.reason}
- **Action needed:** Adjust graylist? Add exception rule?
`).join('')}

## Passed Files (good)

${results.filter(r => r.action === 'pass').map(r => `- ✅ ${r.file}`).join('\n')}

## Rejected Files (correctly blocked)

${results.filter(r => r.action === 'reject').map(r => `- 🛑 ${r.file} — ${r.reason}`).join('\n')}

---

*Audit generated by Content Shield — all success is by Allah's favour.*
`;

  fs.writeFileSync(reportPath, report);
  console.log(`📄 Audit report: ${reportPath}`);
  console.log(`\nSummary: ${passes} pass, ${falsePositives} flagged, ${blocks} rejected`);

  return { results, falsePositives, passes, blocks };
}

// Run
if (require.main === module) {
  const stats = audit();
  process.exit(stats.falsePositives > 5 ? 1 : 0); // alert if many false positives
}

module.exports = { audit };
