#!/usr/bin/env node

/**
 * Content Shield — Weekly Report Generator
 * Outputs efficacy metrics: blocks, false positives, pending reviews
 */

const fs = require('fs');
const path = require('path');

const logPath = path.join(__dirname, '..', 'reports', 'content_shield_log.jsonl');
const decisionsPath = path.join(__dirname, '..', 'reviews', 'decisions.jsonl');
const outputDir = path.join(__dirname, '..', 'reports');

/**
 * Read all log entries for the past week
 */
function getWeeklyLogs() {
  if (!fs.existsSync(logPath)) return [];
  const lines = fs.readFileSync(logPath, 'utf8').trim().split('\n');
  const oneWeekAgo = new Date();
  oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

  return lines.map(line => JSON.parse(line)).filter(entry => {
    const entryDate = new Date(entry.timestamp);
    return entryDate > oneWeekAgo;
  });
}

/**
 * Generate summary statistics
 */
function generateReport() {
  const logs = getWeeklyLogs();
  const decisions = fs.existsSync(decisionsPath)
    ? fs.readFileSync(decisionsPath, 'utf8').trim().split('\n').filter(l => l).map(l => JSON.parse(l))
    : [];

  // Aggregate
  const stats = {
    period: '7 days',
    generatedAt: new Date().toISOString(),
    total_checked: logs.length,
    auto_rejected: logs.filter(l => l.action === 'reject').length,
    flagged_for_review: logs.filter(l => l.action === 'flag_for_review').length,
    passed: logs.filter(l => l.action === 'pass').length,
    by_category: {},
    false_positives: 0,
    true_positives: 0
  };

  // Categorize
  logs.forEach(entry => {
    const cat = entry.category || 'uncategorized';
    stats.by_category[cat] = (stats.by_category[cat] || 0) + 1;
  });

  // Calculate false/true positives (based on human decisions)
  decisions.forEach(dec => {
    if (dec.decision === 'false_positive') {
      stats.false_positives++;
    } else if (dec.decision === 'true_positive') {
      stats.true_positives++;
    }
  });

  // Write report
  const reportMarkdown = `# Content Shield Weekly Report

**Period:** ${stats.period}
**Generated:** ${stats.generatedAt}

## 📊 Summary

| Metric | Count | % |
|--------|------|---|
| Total Checked | ${stats.total_checked} | 100% |
| Auto-Rejected | ${stats.auto_rejected} | ${((stats.auto_rejected/stats.total_checked)*100).toFixed(1)}% |
| Flagged for Review | ${stats.flagged_for_review} | ${((stats.flagged_for_review/stats.total_checked)*100).toFixed(1)}% |
| Passed | ${stats.passed | ((stats.passed/stats.total_checked)*100).toFixed(1)}% |

## 🔍 Categories

${Object.entries(stats.by_category).map(([cat, count]) => `- ${cat}: ${count}`).join('\n')}

## ✅ Human Review Outcomes

- **True Positives:** ${stats.true_positives}
- **False Positives:** ${stats.false_positives}
- **Precision:** ${stats.true_positives + stats.false_positives > 0
  ? (stats.true_positives / (stats.true_positives + stats.false_positives) * 100).toFixed(1)
  : 'N/A'}%

## 🎯 Recommendations

${stats.false_positives > 10 ? '- Review false positive patterns — adjust graylist thresholds' : '- False positive rate acceptable'}

---

* generated by Content Shield — ${stats.generatedAt}*
`;

  const outPath = path.join(outputDir, `filter_efficacy_${new Date().toISOString().split('T')[0]}.md`);
  fs.writeFileSync(outPath, reportMarkdown);
  console.log(`📄 Report written: ${outPath}`);

  return stats;
}

// CLI
if (require.main === module) {
  const stats = generateReport();
  console.log('Report generated:', JSON.stringify(stats, null, 2));
}

module.exports = { generateReport, getWeeklyLogs };
